<?php

namespace Database\Seeders;

use App\Models\Collection;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CollectionsAndProductsSeeder extends Seeder
{
    public function run(): void
    {
        $data = $this->catalog();
        $order = 0;

        foreach ($data as $skuPrefix => $collectionData) {
            $collection = Collection::updateOrCreate(
                ['slug' => Str::slug($collectionData['name'])],
                [
                    'name' => $collectionData['name'],
                    'description' => $collectionData['description'],
                    'icon' => $collectionData['icon'],
                    'color' => $collectionData['color'],
                    'sort_order' => $order++,
                    'is_active' => true,
                ]
            );

            $productOrder = 0;
            foreach ($collectionData['products'] as $index => $p) {
                $number = str_pad((string) ($index + 1), 3, '0', STR_PAD_LEFT);
                $sku = "{$skuPrefix}-{$number}";

                Product::updateOrCreate(
                    ['sku' => $sku],
                    [
                        'name' => $p['name'],
                        'short_name' => $p['name'],
                        'slug' => Product::uniqueSlug(Str::slug($p['name'])),
                        'category_id' => null,
                        'collection_id' => $collection->id,
                        'type' => 'servicio',
                        'short_description' => $p['short'],
                        'description' => $p['description']."\n\nConcepto visual sugerido: ".$p['image_idea'],
                        'benefits' => implode("\n", array_map(fn ($b) => "- {$b}", $p['benefits'])),
                        'features' => implode("\n", array_map(fn ($f) => "- {$f}", $p['features'])),
                        'price' => $p['price'],
                        'old_price' => null,
                        'currency' => 'MXN',
                        'pricing_model' => $p['pricing_model'],
                        'price_prefix_text' => 'Desde',
                        'tax_included' => false,
                        'availability' => 'disponible',
                        'status' => 'borrador',
                        'main_image' => null,
                        'video_url' => null,
                        'url' => null,
                        'demo_url' => null,
                        'whatsapp_url' => null,
                        'whatsapp_message' => $p['whatsapp'],
                        'tags' => [$collectionData['name']],
                        'keywords' => $p['keywords'],
                        'seo_text' => $p['short'],
                        'meta_title' => $p['name'].' | NODO 360',
                        'meta_description' => $p['short'],
                        'structured_data' => null,
                        'published_at' => null,
                        'sort_order' => $productOrder++,
                        'is_featured' => false,
                    ]
                );
            }
        }
    }

    protected function catalog(): array
    {
        return [
            'IA' => [
                'name' => 'Inteligencia Artificial',
                'description' => 'Agentes de inteligencia artificial que atienden, venden y dan seguimiento a tus clientes de forma automática.',
                'icon' => 'cpu-chip',
                'color' => '#2563EB',
                'products' => [
                    [
                        'name' => 'Agente IA para WhatsApp',
                        'short' => 'Atiende, responde y vende por WhatsApp las 24 horas con un agente de inteligencia artificial entrenado con la voz de tu marca.',
                        'description' => 'El Agente IA para WhatsApp de NODO 360 conversa con tus clientes en tiempo real, responde preguntas frecuentes, comparte tu catálogo y deriva a un asesor humano cuando la conversación lo requiere. Se integra con la API oficial de WhatsApp Business y aprende de tu base de conocimiento para dar respuestas precisas y consistentes.',
                        'benefits' => ['Atención inmediata 24/7 sin perder mensajes', 'Reduce tiempos de respuesta y aumenta la conversión', 'Libera a tu equipo de preguntas repetitivas'],
                        'features' => ['Integración con WhatsApp Business API', 'Entrenamiento con tu catálogo y preguntas frecuentes', 'Escalamiento automático a un asesor humano'],
                        'keywords' => 'agente ia whatsapp, chatbot whatsapp, atencion automatizada, ia conversacional',
                        'image_idea' => 'Smartphone con burbuja de chat futurista, gradiente azul-violeta, icono de WhatsApp estilizado.',
                        'whatsapp' => 'Hola, quiero información sobre el Agente IA para WhatsApp de NODO 360.',
                        'price' => 4990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'Agente IA para Ventas',
                        'short' => 'Un vendedor virtual que califica prospectos, resuelve objeciones y agenda citas automáticamente.',
                        'description' => 'El Agente IA para Ventas de NODO 360 acompaña a tus prospectos durante todo el proceso comercial: responde dudas sobre tus productos, presenta opciones según sus necesidades y agenda la siguiente cita con tu equipo de ventas, todo sin intervención humana.',
                        'benefits' => ['Califica prospectos automáticamente', 'Aumenta la tasa de cierre', 'Disponible en todos los canales de contacto'],
                        'features' => ['Guiones de venta configurables', 'Calificación de leads por intención de compra', 'Agenda integrada'],
                        'keywords' => 'agente ia ventas, vendedor virtual, automatizacion comercial',
                        'image_idea' => 'Figura de asistente digital con gráfica de crecimiento, tonos azul y rojo NODO.',
                        'whatsapp' => 'Hola, quiero información sobre el Agente IA para Ventas de NODO 360.',
                        'price' => 5990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'Agente IA para Atención al Cliente',
                        'short' => 'Resuelve dudas, da seguimiento a pedidos y soporta a tus clientes sin filas de espera.',
                        'description' => 'Diseñado para reducir la carga operativa de tu equipo de soporte, el Agente IA para Atención al Cliente responde preguntas frecuentes, da seguimiento a pedidos y escala casos complejos al área correspondiente, manteniendo un tono consistente con tu marca.',
                        'benefits' => ['Reduce el tiempo de espera de tus clientes', 'Disminuye la carga del equipo de soporte', 'Mejora la satisfacción del cliente'],
                        'features' => ['Base de conocimiento configurable', 'Historial de conversaciones', 'Reportes de satisfacción'],
                        'keywords' => 'agente ia atencion al cliente, soporte automatizado, ia servicio al cliente',
                        'image_idea' => 'Icono de auriculares de soporte fusionado con un nodo digital, fondo blanco con gradiente sutil.',
                        'whatsapp' => 'Hola, quiero información sobre el Agente IA para Atención al Cliente de NODO 360.',
                        'price' => 4990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'Agente IA para Agendar Citas',
                        'short' => 'Agenda, confirma y recuerda citas automáticamente, sin choques de horario ni llamadas perdidas.',
                        'description' => 'El Agente IA para Agendar Citas conecta tu calendario con WhatsApp, redes sociales y tu sitio web para que tus clientes reserven un horario disponible, reciban confirmaciones y recordatorios automáticos, reduciendo las inasistencias.',
                        'benefits' => ['Elimina los choques de horario', 'Reduce inasistencias con recordatorios automáticos', 'Disponible fuera de horario de oficina'],
                        'features' => ['Sincronización con calendario', 'Confirmaciones y recordatorios automáticos', 'Reprogramación sin intervención humana'],
                        'keywords' => 'agenda citas ia, reservas automaticas, agente ia citas',
                        'image_idea' => 'Calendario digital con check azul y acentos rojos, estilo minimalista.',
                        'whatsapp' => 'Hola, quiero información sobre el Agente IA para Agendar Citas de NODO 360.',
                        'price' => 3990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'Agente IA para Cotizaciones',
                        'short' => 'Genera cotizaciones personalizadas en segundos a partir de las necesidades de cada cliente.',
                        'description' => 'El Agente IA para Cotizaciones interpreta las necesidades del cliente y genera una propuesta con precios, condiciones y tiempos de entrega, lista para enviarse por WhatsApp, correo o descargar en PDF.',
                        'benefits' => ['Cotiza en segundos, no en horas', 'Reduce errores de captura', 'Mejora la experiencia del cliente'],
                        'features' => ['Plantillas de cotización personalizables', 'Cálculo automático de precios', 'Envío directo por WhatsApp o email'],
                        'keywords' => 'cotizador ia, cotizaciones automaticas, agente ia cotizaciones',
                        'image_idea' => 'Documento tipo cotización con sello digital azul-violeta y símbolo de rayo IA.',
                        'whatsapp' => 'Hola, quiero información sobre el Agente IA para Cotizaciones de NODO 360.',
                        'price' => 4490, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'Agente IA para Seguimiento de Prospectos',
                        'short' => 'Da seguimiento constante a tus prospectos hasta convertirlos en clientes, sin que se te escape ninguno.',
                        'description' => 'El Agente IA para Seguimiento de Prospectos identifica leads fríos, reactiva conversaciones detenidas y avisa a tu equipo de ventas cuando un prospecto está listo para cerrar, evitando fugas en el embudo comercial.',
                        'benefits' => ['Ningún prospecto se queda sin seguimiento', 'Reactiva leads fríos automáticamente', 'Prioriza a los prospectos más calientes'],
                        'features' => ['Segmentación automática de prospectos', 'Recordatorios y reactivación programada', 'Alertas al equipo de ventas'],
                        'keywords' => 'seguimiento de prospectos ia, nurturing automatizado, agente ia leads',
                        'image_idea' => 'Embudo digital con puntos de luz descendiendo, colores azul y violeta.',
                        'whatsapp' => 'Hola, quiero información sobre el Agente IA para Seguimiento de Prospectos de NODO 360.',
                        'price' => 4490, 'pricing_model' => 'mensual',
                    ],
                ],
            ],
            'AUT' => [
                'name' => 'Automatización Empresarial',
                'description' => 'Conectamos tus sistemas y procesos para eliminar tareas manuales repetitivas.',
                'icon' => 'bolt',
                'color' => '#7C3AED',
                'products' => [
                    [
                        'name' => 'Automatización Empresarial',
                        'short' => 'Conecta tus herramientas y automatiza procesos repetitivos para que tu equipo se enfoque en lo importante.',
                        'description' => 'El servicio de Automatización Empresarial de NODO 360 identifica los procesos manuales de tu operación y los conecta mediante flujos automatizados entre tus sistemas actuales, reduciendo errores y tiempos operativos.',
                        'benefits' => ['Reduce tareas manuales repetitivas', 'Disminuye errores operativos', 'Libera tiempo de tu equipo para tareas estratégicas'],
                        'features' => ['Diagnóstico de procesos', 'Integración entre sistemas existentes', 'Flujos de trabajo automatizados'],
                        'keywords' => 'automatizacion empresarial, automatizacion de procesos, eficiencia operativa',
                        'image_idea' => 'Engranajes conectados por líneas de luz azul y violeta sobre fondo blanco.',
                        'whatsapp' => 'Hola, quiero información sobre Automatización Empresarial de NODO 360.',
                        'price' => 6990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'Automatización de Ventas',
                        'short' => 'Automatiza el seguimiento comercial desde el primer contacto hasta el cierre de venta.',
                        'description' => 'Automatiza recordatorios, seguimientos y actualizaciones del embudo de ventas para que ningún prospecto se pierda y tu equipo comercial trabaje sobre información siempre actualizada.',
                        'benefits' => ['Embudo de ventas siempre actualizado', 'Seguimiento automático a prospectos', 'Menos tareas administrativas para el equipo de ventas'],
                        'features' => ['Integración con CRM', 'Recordatorios automáticos', 'Reportes de desempeño comercial'],
                        'keywords' => 'automatizacion de ventas, crm automatizado, embudo de ventas',
                        'image_idea' => 'Gráfica de embudo ascendente con acentos rojos sobre fondo azul oscuro.',
                        'whatsapp' => 'Hola, quiero información sobre Automatización de Ventas de NODO 360.',
                        'price' => 5990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'Automatización de Inventarios',
                        'short' => 'Controla existencias, alertas de stock y reabastecimiento sin hojas de cálculo manuales.',
                        'description' => 'El servicio de Automatización de Inventarios sincroniza tus existencias entre canales de venta, genera alertas de stock bajo y facilita el reabastecimiento oportuno, evitando pérdidas por falta o exceso de inventario.',
                        'benefits' => ['Evita quiebres y excesos de inventario', 'Sincroniza existencias entre canales', 'Alertas automáticas de reabastecimiento'],
                        'features' => ['Sincronización multicanal', 'Alertas de stock mínimo', 'Reportes de rotación de inventario'],
                        'keywords' => 'automatizacion de inventarios, control de stock, gestion de inventario',
                        'image_idea' => 'Cajas apiladas con código de barras digital y gráfica de nivel de stock.',
                        'whatsapp' => 'Hola, quiero información sobre Automatización de Inventarios de NODO 360.',
                        'price' => 5990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'Automatización de Reservas',
                        'short' => 'Gestiona reservas y disponibilidad en tiempo real sin intervención manual.',
                        'description' => 'Ideal para negocios con horarios y disponibilidad limitada, este servicio automatiza la gestión de reservas, evita sobrecupos y envía confirmaciones y recordatorios a tus clientes.',
                        'benefits' => ['Elimina sobrecupos y errores de agenda', 'Confirmaciones automáticas', 'Disponibilidad visible en tiempo real'],
                        'features' => ['Calendario de disponibilidad en tiempo real', 'Confirmaciones y recordatorios automáticos', 'Panel de gestión de reservas'],
                        'keywords' => 'automatizacion de reservas, sistema de reservas, gestion de citas',
                        'image_idea' => 'Calendario digital con espacios reservados en azul y disponibles en blanco.',
                        'whatsapp' => 'Hola, quiero información sobre Automatización de Reservas de NODO 360.',
                        'price' => 4990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'Automatización de Cobranza',
                        'short' => 'Da seguimiento a pagos pendientes y recordatorios de cobro sin desgastar la relación con tus clientes.',
                        'description' => 'Automatiza el proceso de cobranza con recordatorios oportunos, seguimiento a facturas vencidas y reportes de cartera, manteniendo una comunicación profesional y consistente con tus clientes.',
                        'benefits' => ['Mejora el flujo de efectivo', 'Reduce la cartera vencida', 'Comunicación de cobro consistente y profesional'],
                        'features' => ['Recordatorios automáticos de pago', 'Seguimiento de facturas vencidas', 'Reportes de cartera'],
                        'keywords' => 'automatizacion de cobranza, recordatorios de pago, gestion de cartera',
                        'image_idea' => 'Factura digital con reloj de recordatorio y acento rojo de alerta.',
                        'whatsapp' => 'Hola, quiero información sobre Automatización de Cobranza de NODO 360.',
                        'price' => 4990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'Automatización de Email Marketing',
                        'short' => 'Envía el mensaje correcto al contacto correcto en el momento adecuado, de forma automática.',
                        'description' => 'Configura secuencias automáticas de correo para dar la bienvenida, nutrir prospectos y reactivar clientes, basadas en el comportamiento e intereses de cada contacto.',
                        'benefits' => ['Comunicación oportuna sin esfuerzo manual', 'Aumenta la tasa de apertura y clics', 'Nutre prospectos hasta convertirlos en clientes'],
                        'features' => ['Secuencias automáticas configurables', 'Segmentación por comportamiento', 'Reportes de apertura y clics'],
                        'keywords' => 'automatizacion email marketing, secuencias de correo, nutricion de leads',
                        'image_idea' => 'Sobre digital con múltiples flechas de envío automatizado, gradiente violeta.',
                        'whatsapp' => 'Hola, quiero información sobre Automatización de Email Marketing de NODO 360.',
                        'price' => 3990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'Automatización de Redes Sociales',
                        'short' => 'Programa y publica contenido en tus redes sociales de forma constante y sin esfuerzo diario.',
                        'description' => 'Automatiza la programación y publicación de contenido en tus canales sociales, manteniendo una presencia constante sin necesidad de publicar manualmente cada día.',
                        'benefits' => ['Presencia constante en redes sociales', 'Ahorra horas de trabajo manual', 'Calendario editorial siempre organizado'],
                        'features' => ['Programación multicanal', 'Calendario editorial visual', 'Reportes de publicación'],
                        'keywords' => 'automatizacion redes sociales, programacion de contenido, gestion de redes',
                        'image_idea' => 'Calendario editorial con iconos de redes sociales flotando, tonos azul-violeta.',
                        'whatsapp' => 'Hola, quiero información sobre Automatización de Redes Sociales de NODO 360.',
                        'price' => 4490, 'pricing_model' => 'mensual',
                    ],
                ],
            ],
            'SOF' => [
                'name' => 'Software Empresarial',
                'description' => 'Sistemas y plataformas a la medida para operar y escalar tu negocio.',
                'icon' => 'squares-2x2',
                'color' => '#0F172A',
                'products' => [
                    [
                        'name' => 'CRM Inteligente',
                        'short' => 'Organiza a tus prospectos y clientes en un solo lugar con inteligencia artificial integrada.',
                        'description' => 'El CRM Inteligente de NODO 360 centraliza la información de tus prospectos y clientes, prioriza oportunidades con ayuda de inteligencia artificial y da visibilidad completa del embudo comercial a tu equipo.',
                        'benefits' => ['Toda la información comercial en un solo lugar', 'Prioriza oportunidades con IA', 'Visibilidad total del embudo de ventas'],
                        'features' => ['Pipeline visual tipo Kanban', 'Historial de interacciones por contacto', 'Reportes y métricas comerciales'],
                        'keywords' => 'crm inteligente, crm con ia, gestion de clientes',
                        'image_idea' => 'Panel Kanban digital con tarjetas de clientes, colores azul y blanco.',
                        'whatsapp' => 'Hola, quiero información sobre el CRM Inteligente de NODO 360.',
                        'price' => 7990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'Sistemas a la Medida',
                        'short' => 'Desarrollamos el sistema que tu operación necesita, adaptado a tus procesos reales.',
                        'description' => 'Diseñamos y desarrollamos sistemas a la medida cuando las soluciones genéricas no se ajustan a tu operación, garantizando que la herramienta se adapte a tu negocio y no al revés.',
                        'benefits' => ['Solución adaptada a tus procesos exactos', 'Escalable conforme crece tu negocio', 'Soporte y mantenimiento incluido'],
                        'features' => ['Levantamiento de requerimientos', 'Desarrollo a la medida', 'Documentación técnica y capacitación'],
                        'keywords' => 'sistemas a la medida, desarrollo de software, software personalizado',
                        'image_idea' => 'Planos digitales de software con bloques modulares en azul y violeta.',
                        'whatsapp' => 'Hola, quiero información sobre Sistemas a la Medida de NODO 360.',
                        'price' => 25000, 'pricing_model' => 'proyecto',
                    ],
                    [
                        'name' => 'Sistema para Hoteles y Moteles',
                        'short' => 'Gestiona reservaciones, tarifas y ocupación de tu hotel o motel desde un solo sistema.',
                        'description' => 'Sistema especializado para la operación diaria de hoteles y moteles: control de reservaciones, disponibilidad de habitaciones, tarifas por temporada y reportes de ocupación.',
                        'benefits' => ['Control total de la ocupación en tiempo real', 'Reduce errores de sobreventa', 'Reportes de ingresos por habitación'],
                        'features' => ['Panel de reservaciones y disponibilidad', 'Gestión de tarifas por temporada', 'Reportes de ocupación e ingresos'],
                        'keywords' => 'sistema para hoteles, software hotelero, gestion de moteles',
                        'image_idea' => 'Icono de llave de habitación digital sobre mapa de ocupación por pisos.',
                        'whatsapp' => 'Hola, quiero información sobre el Sistema para Hoteles y Moteles de NODO 360.',
                        'price' => 9990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'Control de Inventarios',
                        'short' => 'Sistema de control de inventarios con alertas y reportes en tiempo real.',
                        'description' => 'Plataforma para el control de existencias, entradas, salidas y valuación de inventario, con alertas automáticas de stock mínimo y reportes de rotación.',
                        'benefits' => ['Visibilidad en tiempo real de tu inventario', 'Alertas de stock mínimo', 'Reportes de valuación y rotación'],
                        'features' => ['Registro de entradas y salidas', 'Alertas de stock mínimo', 'Reportes de valuación de inventario'],
                        'keywords' => 'control de inventarios, sistema de inventario, gestion de almacen',
                        'image_idea' => 'Estantería de almacén digitalizada con indicadores de nivel de stock.',
                        'whatsapp' => 'Hola, quiero información sobre el sistema de Control de Inventarios de NODO 360.',
                        'price' => 6990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'ERP Empresarial',
                        'short' => 'Integra finanzas, inventarios, ventas y operación en una sola plataforma.',
                        'description' => 'El ERP Empresarial de NODO 360 conecta las áreas clave de tu negocio en una sola plataforma, eliminando la duplicidad de información y dando visibilidad completa a la dirección.',
                        'benefits' => ['Información unificada entre áreas', 'Elimina duplicidad de datos', 'Visibilidad completa para la dirección'],
                        'features' => ['Módulos de finanzas, inventario y ventas', 'Reportes ejecutivos integrados', 'Control de accesos por rol'],
                        'keywords' => 'erp empresarial, sistema erp, planificacion de recursos',
                        'image_idea' => 'Red de módulos conectados alrededor de un núcleo central azul.',
                        'whatsapp' => 'Hola, quiero información sobre el ERP Empresarial de NODO 360.',
                        'price' => 14990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'Aplicaciones Móviles',
                        'short' => 'Llevamos tu negocio al bolsillo de tus clientes con una aplicación móvil a la medida.',
                        'description' => 'Desarrollamos aplicaciones móviles para iOS y Android, alineadas a tus procesos de negocio y a la experiencia que quieres ofrecer a tus clientes o colaboradores.',
                        'benefits' => ['Presencia directa en el dispositivo del cliente', 'Experiencia de usuario a la medida', 'Disponible en iOS y Android'],
                        'features' => ['Diseño UX/UI a la medida', 'Publicación en tiendas de aplicaciones', 'Mantenimiento y actualizaciones'],
                        'keywords' => 'aplicaciones moviles, desarrollo de apps, app a la medida',
                        'image_idea' => 'Silueta de teléfono móvil con interfaz de app y acentos rojos NODO.',
                        'whatsapp' => 'Hola, quiero información sobre Aplicaciones Móviles de NODO 360.',
                        'price' => 25000, 'pricing_model' => 'proyecto',
                    ],
                    [
                        'name' => 'Integración de APIs',
                        'short' => 'Conectamos tus sistemas actuales entre sí para que la información fluya sin fricción.',
                        'description' => 'Diseñamos e implementamos integraciones entre tus plataformas actuales mediante APIs, evitando la doble captura de información y automatizando el intercambio de datos entre sistemas.',
                        'benefits' => ['Elimina la doble captura de información', 'Sistemas conectados y sincronizados', 'Reduce errores manuales'],
                        'features' => ['Diagnóstico de integración', 'Desarrollo de conectores a la medida', 'Monitoreo de integraciones activas'],
                        'keywords' => 'integracion de apis, conectores a medida, integracion de sistemas',
                        'image_idea' => 'Nodos conectados por cables de luz representando el flujo de datos entre sistemas.',
                        'whatsapp' => 'Hola, quiero información sobre Integración de APIs de NODO 360.',
                        'price' => 12990, 'pricing_model' => 'proyecto',
                    ],
                ],
            ],
            'GRW' => [
                'name' => 'Growth Marketing',
                'description' => 'Estrategias de marketing digital orientadas a resultados medibles.',
                'icon' => 'rocket-launch',
                'color' => '#DC2626',
                'products' => [
                    [
                        'name' => 'Marketing Inteligente con IA',
                        'short' => 'Estrategias de marketing potenciadas con inteligencia artificial para crecer de forma medible.',
                        'description' => 'Combinamos estrategia de marketing con herramientas de inteligencia artificial para segmentar audiencias, generar contenido y optimizar campañas con base en datos reales.',
                        'benefits' => ['Decisiones basadas en datos, no en suposiciones', 'Campañas optimizadas continuamente', 'Mejor retorno de inversión publicitaria'],
                        'features' => ['Segmentación de audiencias con IA', 'Generación de contenido asistido', 'Reportes de desempeño de campañas'],
                        'keywords' => 'marketing con ia, marketing inteligente, estrategia digital',
                        'image_idea' => 'Gráfica de crecimiento con destello de IA en tonos azul y rojo.',
                        'whatsapp' => 'Hola, quiero información sobre Marketing Inteligente con IA de NODO 360.',
                        'price' => 8990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'Google Ads y Meta Ads',
                        'short' => 'Campañas publicitarias en Google y Meta administradas por especialistas y optimizadas con datos.',
                        'description' => 'Gestionamos tus campañas de Google Ads y Meta Ads (Facebook e Instagram), desde la estrategia y segmentación hasta la optimización continua para mejorar tu costo por resultado.',
                        'benefits' => ['Mayor alcance en los canales donde está tu cliente', 'Optimización continua del presupuesto', 'Reportes claros de retorno de inversión'],
                        'features' => ['Gestión de campañas en Google y Meta', 'Segmentación avanzada de audiencias', 'Reportes mensuales de desempeño'],
                        'keywords' => 'google ads, meta ads, publicidad digital, pauta publicitaria',
                        'image_idea' => 'Logos estilizados de Google y Meta con gráfica de resultados ascendente.',
                        'whatsapp' => 'Hola, quiero información sobre Google Ads y Meta Ads de NODO 360.',
                        'price' => 6990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'Landing Pages de Alta Conversión',
                        'short' => 'Páginas de aterrizaje diseñadas para convertir visitantes en clientes.',
                        'description' => 'Diseñamos landing pages enfocadas en conversión, con estructura persuasiva, carga rápida y llamadas a la acción claras, alineadas a tus campañas de marketing.',
                        'benefits' => ['Mayor tasa de conversión de visitantes', 'Diseño alineado a tus campañas', 'Carga rápida y optimizada para móviles'],
                        'features' => ['Estructura orientada a conversión', 'Formularios de captura integrados', 'Optimización para SEO y redes sociales'],
                        'keywords' => 'landing pages, paginas de aterrizaje, alta conversion',
                        'image_idea' => 'Maqueta de página web en dispositivo móvil con botón de llamada a la acción rojo.',
                        'whatsapp' => 'Hola, quiero información sobre Landing Pages de Alta Conversión de NODO 360.',
                        'price' => 4990, 'pricing_model' => 'proyecto',
                    ],
                    [
                        'name' => 'Optimización para IA, AEO y GEO',
                        'short' => 'Prepara tu contenido para ser encontrado por buscadores tradicionales y motores de IA.',
                        'description' => 'Optimizamos tu sitio y contenido para mejorar su desempeño en buscadores tradicionales (SEO), motores de respuesta como asistentes de IA (AEO) y búsqueda generativa (GEO), sin prometer resultados garantizados en plataformas que NODO 360 no controla.',
                        'benefits' => ['Contenido mejor estructurado para IA y buscadores', 'Mayor claridad semántica del sitio', 'Base sólida para estrategias de contenido'],
                        'features' => ['Auditoría de SEO, AEO y GEO', 'Recomendaciones de datos estructurados', 'Checklist de optimización priorizado'],
                        'keywords' => 'aeo, geo, seo con ia, optimizacion para buscadores',
                        'image_idea' => 'Radar digital escaneando un sitio web, con iconos de buscadores e IA.',
                        'whatsapp' => 'Hola, quiero información sobre Optimización para IA, AEO y GEO de NODO 360.',
                        'price' => 5990, 'pricing_model' => 'proyecto',
                    ],
                    [
                        'name' => 'Email Marketing Inteligente',
                        'short' => 'Campañas de correo segmentadas que llegan al contacto correcto en el momento correcto.',
                        'description' => 'Diseñamos y gestionamos campañas de email marketing segmentadas, con contenido relevante para cada etapa del cliente y reportes de apertura, clics y conversión.',
                        'benefits' => ['Comunicación relevante para cada segmento', 'Mejora la relación con tus contactos', 'Reportes claros de desempeño'],
                        'features' => ['Segmentación de listas de contactos', 'Plantillas de correo profesionales', 'Reportes de apertura y clics'],
                        'keywords' => 'email marketing, campañas de correo, marketing por email',
                        'image_idea' => 'Sobre digital abriéndose con gráfica de apertura de correos.',
                        'whatsapp' => 'Hola, quiero información sobre Email Marketing Inteligente de NODO 360.',
                        'price' => 3990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'Gestión de Redes Sociales',
                        'short' => 'Estrategia, contenido y publicación constante en tus redes sociales.',
                        'description' => 'Nos encargamos de la estrategia de contenido, diseño y publicación en tus redes sociales, manteniendo una presencia de marca consistente y profesional.',
                        'benefits' => ['Presencia de marca consistente', 'Contenido alineado a tu identidad visual', 'Reportes de crecimiento y alcance'],
                        'features' => ['Calendario de contenido mensual', 'Diseño de piezas gráficas', 'Reportes de alcance e interacción'],
                        'keywords' => 'gestion de redes sociales, community management, contenido para redes',
                        'image_idea' => 'Mosaico de publicaciones de redes sociales en tonos de marca NODO.',
                        'whatsapp' => 'Hola, quiero información sobre Gestión de Redes Sociales de NODO 360.',
                        'price' => 5990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'Generación de Contenido con IA',
                        'short' => 'Contenido de marketing generado con inteligencia artificial, revisado y aprobado por tu equipo.',
                        'description' => 'Utilizamos inteligencia artificial para acelerar la generación de textos, descripciones y publicaciones de marketing, siempre con un proceso de revisión y aprobación antes de publicarse.',
                        'benefits' => ['Acelera la producción de contenido', 'Mantiene consistencia de tono de marca', 'Contenido revisado antes de publicarse'],
                        'features' => ['Generación de textos con IA', 'Flujo de revisión y aprobación', 'Variantes de contenido por canal'],
                        'keywords' => 'generacion de contenido con ia, copywriting con ia, contenido de marketing',
                        'image_idea' => 'Pluma digital escribiendo sobre una pantalla, con destellos de IA en azul y violeta.',
                        'whatsapp' => 'Hola, quiero información sobre Generación de Contenido con IA de NODO 360.',
                        'price' => 4490, 'pricing_model' => 'mensual',
                    ],
                ],
            ],
            'IND' => [
                'name' => 'Soluciones por Industria',
                'description' => 'Soluciones de inteligencia artificial adaptadas a los procesos específicos de cada industria.',
                'icon' => 'building-storefront',
                'color' => '#0EA5E9',
                'products' => [
                    [
                        'name' => 'IA para Hoteles y Moteles',
                        'short' => 'Automatiza reservaciones y atención al huésped con inteligencia artificial.',
                        'description' => 'Solución de inteligencia artificial diseñada para hoteles y moteles: atiende consultas de disponibilidad, gestiona reservaciones y da seguimiento a huéspedes antes, durante y después de su estancia.',
                        'benefits' => ['Atención a huéspedes las 24 horas', 'Reduce llamadas y mensajes sin responder', 'Mejora la experiencia de reservación'],
                        'features' => ['Consulta de disponibilidad automatizada', 'Confirmaciones y recordatorios de reservación', 'Seguimiento post-estancia'],
                        'keywords' => 'ia para hoteles, ia para moteles, automatizacion hotelera',
                        'image_idea' => 'Fachada de hotel estilizada con burbuja de chat flotante.',
                        'whatsapp' => 'Hola, quiero información sobre IA para Hoteles y Moteles de NODO 360.',
                        'price' => 6990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'IA para Despachos Jurídicos',
                        'short' => 'Atiende consultas iniciales y agenda citas para tu despacho jurídico automáticamente.',
                        'description' => 'Solución de inteligencia artificial para despachos jurídicos que atiende consultas iniciales de clientes potenciales, clasifica el tipo de caso y agenda una cita con el abogado correspondiente.',
                        'benefits' => ['Filtra y clasifica consultas automáticamente', 'Agenda citas sin intervención manual', 'Mejora el primer contacto con el cliente'],
                        'features' => ['Clasificación de tipo de caso', 'Agenda integrada con el despacho', 'Respuestas basadas en tu área de práctica'],
                        'keywords' => 'ia para abogados, ia para despachos juridicos, automatizacion legal',
                        'image_idea' => 'Balanza de la justicia estilizada con líneas digitales azules.',
                        'whatsapp' => 'Hola, quiero información sobre IA para Despachos Jurídicos de NODO 360.',
                        'price' => 5990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'IA para Clínicas',
                        'short' => 'Agenda citas médicas y resuelve dudas de pacientes de forma automática.',
                        'description' => 'Solución de inteligencia artificial para clínicas y consultorios que gestiona la agenda de citas, envía recordatorios a pacientes y responde preguntas frecuentes sobre servicios y horarios.',
                        'benefits' => ['Reduce inasistencias con recordatorios automáticos', 'Libera a tu equipo de recepción', 'Atención disponible fuera de horario'],
                        'features' => ['Agenda de citas médicas', 'Recordatorios automáticos a pacientes', 'Respuestas a preguntas frecuentes'],
                        'keywords' => 'ia para clinicas, ia para consultorios, agenda medica automatizada',
                        'image_idea' => 'Cruz médica estilizada junto a un calendario digital azul.',
                        'whatsapp' => 'Hola, quiero información sobre IA para Clínicas de NODO 360.',
                        'price' => 5990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'IA para Inmobiliarias',
                        'short' => 'Califica prospectos y agenda visitas a propiedades de forma automática.',
                        'description' => 'Solución de inteligencia artificial para inmobiliarias que responde consultas sobre propiedades disponibles, califica el interés del prospecto y agenda visitas con el asesor correspondiente.',
                        'benefits' => ['Responde consultas de propiedades al instante', 'Califica prospectos por nivel de interés', 'Agenda visitas automáticamente'],
                        'features' => ['Catálogo de propiedades integrado', 'Calificación automática de prospectos', 'Agenda de visitas'],
                        'keywords' => 'ia para inmobiliarias, ia bienes raices, automatizacion inmobiliaria',
                        'image_idea' => 'Silueta de casa con pin de ubicación digital y acentos azules.',
                        'whatsapp' => 'Hola, quiero información sobre IA para Inmobiliarias de NODO 360.',
                        'price' => 5990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'IA para Restaurantes',
                        'short' => 'Toma reservaciones, pedidos y responde preguntas frecuentes de tu restaurante.',
                        'description' => 'Solución de inteligencia artificial para restaurantes que gestiona reservaciones, responde preguntas sobre el menú y horarios, y puede recibir pedidos para llevar o a domicilio.',
                        'benefits' => ['Reduce llamadas para reservaciones', 'Disponible en horas pico sin saturarse', 'Mejora la experiencia del comensal'],
                        'features' => ['Reservaciones automatizadas', 'Respuestas sobre menú y horarios', 'Recepción de pedidos'],
                        'keywords' => 'ia para restaurantes, reservaciones automaticas, ia gastronomia',
                        'image_idea' => 'Plato estilizado con burbuja de chat y acento rojo NODO.',
                        'whatsapp' => 'Hola, quiero información sobre IA para Restaurantes de NODO 360.',
                        'price' => 4990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'IA para Escuelas',
                        'short' => 'Atiende consultas de admisión e informa a padres de familia automáticamente.',
                        'description' => 'Solución de inteligencia artificial para instituciones educativas que atiende consultas de admisión, informa sobre planes de estudio y costos, y agenda citas informativas con el área correspondiente.',
                        'benefits' => ['Atiende consultas de admisión todo el día', 'Reduce carga en el área administrativa', 'Agenda citas informativas automáticamente'],
                        'features' => ['Información de planes de estudio y costos', 'Agenda de citas informativas', 'Seguimiento a familias interesadas'],
                        'keywords' => 'ia para escuelas, ia educacion, automatizacion admisiones',
                        'image_idea' => 'Birrete de graduación estilizado con líneas digitales azul-violeta.',
                        'whatsapp' => 'Hola, quiero información sobre IA para Escuelas de NODO 360.',
                        'price' => 4990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'IA para Mariachis y Eventos',
                        'short' => 'Cotiza y agenda contrataciones para eventos de forma automática, incluso en fin de semana.',
                        'description' => 'Solución de inteligencia artificial pensada para negocios de eventos y grupos musicales, que cotiza servicios según fecha y tipo de evento, y agenda la contratación sin depender de que alguien conteste el teléfono.',
                        'benefits' => ['Cotiza y agenda incluso fuera de horario', 'No pierdes contrataciones por no contestar a tiempo', 'Disponible en fines de semana y días festivos'],
                        'features' => ['Cotización según tipo de evento', 'Agenda de disponibilidad en tiempo real', 'Confirmación automática de apartado'],
                        'keywords' => 'ia para eventos, ia para mariachis, automatizacion de contrataciones',
                        'image_idea' => 'Nota musical estilizada junto a un calendario de eventos digital.',
                        'whatsapp' => 'Hola, quiero información sobre IA para Mariachis y Eventos de NODO 360.',
                        'price' => 3990, 'pricing_model' => 'mensual',
                    ],
                ],
            ],
            'TRA' => [
                'name' => 'Transformación Digital',
                'description' => 'Infraestructura, seguridad y consultoría para digitalizar tu operación.',
                'icon' => 'globe-alt',
                'color' => '#1D4ED8',
                'products' => [
                    [
                        'name' => 'Infraestructura Cloud',
                        'short' => 'Diseñamos e implementamos la infraestructura en la nube que tu operación necesita.',
                        'description' => 'Diseñamos, migramos e implementamos infraestructura en la nube adaptada al tamaño y necesidades de tu operación, priorizando disponibilidad, escalabilidad y costo.',
                        'benefits' => ['Infraestructura escalable según tu crecimiento', 'Mayor disponibilidad y estabilidad', 'Optimización de costos en la nube'],
                        'features' => ['Diagnóstico de infraestructura actual', 'Migración a la nube', 'Monitoreo de disponibilidad'],
                        'keywords' => 'infraestructura cloud, migracion a la nube, servidores en la nube',
                        'image_idea' => 'Nube digital con servidores estilizados y líneas de conexión azules.',
                        'whatsapp' => 'Hola, quiero información sobre Infraestructura Cloud de NODO 360.',
                        'price' => 9990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'Hosting y Dominios',
                        'short' => 'Alojamiento web confiable y gestión de dominios para que tu sitio esté siempre disponible.',
                        'description' => 'Ofrecemos servicios de hosting y administración de dominios con monitoreo de disponibilidad, respaldos periódicos y soporte técnico especializado.',
                        'benefits' => ['Sitio web siempre disponible', 'Respaldos periódicos incluidos', 'Soporte técnico especializado'],
                        'features' => ['Hosting administrado', 'Gestión de dominios', 'Respaldos automáticos'],
                        'keywords' => 'hosting, dominios, alojamiento web',
                        'image_idea' => 'Servidor estilizado con candado de seguridad y globo terráqueo digital.',
                        'whatsapp' => 'Hola, quiero información sobre Hosting y Dominios de NODO 360.',
                        'price' => 990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'Ciberseguridad',
                        'short' => 'Protege tu información y la de tus clientes con buenas prácticas de ciberseguridad.',
                        'description' => 'Evaluamos y fortalecemos la seguridad de tus sistemas, sitios web y bases de datos, implementando buenas prácticas y monitoreo para reducir el riesgo de incidentes de seguridad.',
                        'benefits' => ['Reduce el riesgo de incidentes de seguridad', 'Protege la información de tus clientes', 'Cumple con buenas prácticas del sector'],
                        'features' => ['Auditoría de seguridad', 'Implementación de buenas prácticas', 'Monitoreo de vulnerabilidades'],
                        'keywords' => 'ciberseguridad, seguridad informatica, proteccion de datos',
                        'image_idea' => 'Escudo digital con candado, tonos azul oscuro y acentos rojos.',
                        'whatsapp' => 'Hola, quiero información sobre Ciberseguridad de NODO 360.',
                        'price' => 7990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'Dashboards Ejecutivos',
                        'short' => 'Visualiza los indicadores clave de tu negocio en un solo panel, en tiempo real.',
                        'description' => 'Diseñamos dashboards ejecutivos que consolidan la información de tus distintas áreas en indicadores claros, facilitando la toma de decisiones basada en datos.',
                        'benefits' => ['Decisiones basadas en datos en tiempo real', 'Indicadores clave en un solo lugar', 'Menos tiempo armando reportes manuales'],
                        'features' => ['Conexión con tus fuentes de datos', 'Indicadores y gráficas personalizadas', 'Actualización automática de datos'],
                        'keywords' => 'dashboards ejecutivos, tableros de control, business intelligence',
                        'image_idea' => 'Panel de control con gráficas y KPIs en azul, violeta y blanco.',
                        'whatsapp' => 'Hola, quiero información sobre Dashboards Ejecutivos de NODO 360.',
                        'price' => 6990, 'pricing_model' => 'mensual',
                    ],
                    [
                        'name' => 'Consultoría en Transformación Digital',
                        'short' => 'Acompañamiento estratégico para digitalizar tu operación de forma ordenada y con resultados medibles.',
                        'description' => 'Brindamos consultoría en transformación digital para diagnosticar el nivel de madurez tecnológica de tu empresa y diseñar una hoja de ruta priorizada de digitalización.',
                        'benefits' => ['Hoja de ruta clara de digitalización', 'Priorización de proyectos según impacto', 'Acompañamiento estratégico continuo'],
                        'features' => ['Diagnóstico de madurez digital', 'Hoja de ruta de transformación', 'Seguimiento periódico de avances'],
                        'keywords' => 'transformacion digital, consultoria digital, digitalizacion empresarial',
                        'image_idea' => 'Brújula digital sobre un mapa de ruta de transformación, tonos azul y violeta.',
                        'whatsapp' => 'Hola, quiero información sobre Consultoría en Transformación Digital de NODO 360.',
                        'price' => 8990, 'pricing_model' => 'mensual',
                    ],
                ],
            ],
        ];
    }
}
